### ISSUE TITLE
Scanlist 

### ISSUE THREAD

**Issue by f5nlg** [sq5bpf/uvk5-reverse-engineering#10]
Hello ,
is it not better to put all memory on scanlist 1+2 when we write memory on the chirp file?
if you have many memories , it's borring to add them on scanlist

73 de F5NLG / Jean-Philippe .

**Comment by sq5bpf** [comment]
Just use chirp functionality:
enable View -> Show extra fields
mark a range of channels, right click on the scanlist field and select 1+2
