### ISSUE TITLE
Update of frequency range info in the unlock settings menu

### ISSUE THREAD

**Issue by pawol** [sq5bpf/uvk5-reverse-engineering#12]
Update of frequency range info in the unlock settings menu / f-lock
according to hidden menu in the original CPS

![Untitled](https://github.com/sq5bpf/uvk5-reverse-engineering/assets/13277626/f450eb58-c17b-4dab-be5d-d50fa8f1c004)

**Comment by pawol** [comment]
Can be closed. I see the latest chip has that updated info

**Comment by pawol** [comment]
Can be closed. I see the latest chip has that updated info

**Comment by pawol** [comment]
My mistake, The ticket is valid

**Comment by RE3CON** [comment]
do you mean in the software Advance para password to show: qs975gcms
to hide type: rmgcms
???

**Comment by ludwich66** [comment]
> do you mean in the software Advance para password to show: qs975gcms
> to hide type: rmgcms
> ???
Please see this link!

https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/Official_Config-Tool

Is it clearly described?

Greatings Ludwich

**Comment by RE3CON** [comment]
sure it is very well described. Not sure if pawol mean to make changes inside the CPS tool or how to make advanved menu accessible. If its about the program I can make some changes even if its protected crypted executable to unpack and look with ollydbg in binaries.
