### ISSUE TITLE
Missing columns in the Chirp

### ISSUE THREAD

**Issue by pawol** [sq5bpf/uvk5-reverse-engineering#3]
I have found missing columns like "Encryption flag" Busy channel lock", "Frequency reverse", "AM flag".
In fact we can have FM wide, FM narrow, AM wide, AM narrow - the modulation does is not related on channel width and opposite.

**Comment by sq5bpf** [comment]
implemented AM (wide AM) and NAM (narrow AM)

**Comment by pawol** [comment]
what about encryption flag and freq reverse?

**Comment by sq5bpf** [comment]
enryption, bclo and freq reverse are all in the extra settings (right click o the memory in chirp, and first confirm that you have at least chirp-next from 20230515 or later)
