### ISSUE TITLE
Wrong selector in the column "mode"

### ISSUE THREAD

**Issue by pawol** [sq5bpf/uvk5-reverse-engineering#4]
I see that column "mode"allows to select AM/FM/NFM. 
AM flag should be in sepatare column because it is possible to se in the radio AM wide or AM narrow. AM settings are independend

**Comment by sq5bpf** [comment]
implemented AM and NAM (which is AM with wide and narrow filters)

if you want to have the latest updates to the chirp driver, then grab it from https://github.com/sq5bpf/chirp
