### ISSUE TITLE
Missing columns on channel list

### ISSUE THREAD

**Issue by pawol** [sq5bpf/uvk5-reverse-engineering#6]
Missing collumns on channel list:
- Busy Channel Lock
- Encryption Flag
- PTT ID
- Frequency reverse
- DTMF decode

**Comment by pawol** [comment]
Ok. I have found missing settings by pressing right mouse key on channel list, then properties and extra.
This is extremally not intuitive to find

**Comment by sq5bpf** [comment]
This is the way chirp works. It has nothing to do with this driver.  

The chirp developers are working on making the extra settings available as columns in the channel list. Follow chirp development if you're interested. 

I agree that this is not intuitive. My UV-K5 driver had a hack to show these settings in the comment field, but it was an abuse of the way chirp works, and was removed on the chirp developers request.

**Comment by pawol** [comment]
So the ticket  can be closed
