### ISSUE TITLE
Logo string buffer overrun?

### ISSUE THREAD

**Issue by egzumer** [sq5bpf/uvk5-reverse-engineering#9]
12 characters logo string doesn't work. Looks like buffer overrun. "Browser" tab shows some weird characters in the logo_line fields.
As an example when I enter "yellowhammer" on the Settings tab, I get "yellowhammerÿÿÿÿ" on the Browser tab.
When I send this to radio I get text that is shifted and divided into two lines.

**Comment by sq5bpf** [comment]
Fixed, the limit is 11 characters.

Thanks for reporting.

**Comment by egzumer** [comment]
The original quansheng software supports up to 12 characters.

**Comment by sq5bpf** [comment]
You're right.

Should be fixed now.

**Comment by egzumer** [comment]
Works like a charm, thanks.
